version: 2

sources:
  - name: raw
    tables:
      - name: raw_customers
        data_tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
                min_value: 30
        columns:
          - name: id
            data_tests:
              - unique
              - not_null
          - name: first_name
          - name: last_name

      - name: raw_orders
        columns:
          - name: id
            data_tests:
              - unique
              - not_null
          - name: user_id
            data_tests:
              - relationships:
                  to: source('raw','raw_customers')
                  field: id
          - name: order_data
          - name: status

      - name: raw_payments
        columns:
          - name: id
            data_tests:
              - unique
              - not_null
          - name: order_id
            data_tests:
              - relationships:
                  to: source('raw','raw_orders')
                  field: id
          - name: payment_method
          - name: amount
            data_tests:
              - dbt_expectations.expect_column_max_to_be_between:
                  min_value: 3000
                  max_value: 4000
