version: 2

models:
  - name: stg_customers
    description: The raw customer data with some colum renaming.
    columns:
      - name: customer_id
        description: The customer id
        data_tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              arguments:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
