version: 2
sources:
  - name: public
    tables:
      - name: names
        columns:
          - name: id
          - name: first_name
          - name: last_name

      - name: additional_data
        columns:
          - name: id
          - name: mail
          - name: gender

